# Generated by Django 3.0.4 on 2020-03-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('counteraction', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('income_action', models.CharField(max_length=20)),
                ('foreign_aid_action', models.CharField(max_length=20)),
                ('coins', models.IntegerField()),
                ('card1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_requests_created', to='gameplay.Card')),
                ('card2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameplay.Card')),
            ],
        ),
    ]
