# Generated by Django 3.0.4 on 2020-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
