# Generated by Django 3.0.4 on 2020-03-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_card_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(default='PENDING', max_length=20),
            preserve_default=False,
        ),
    ]
