# Generated by Django 3.0.4 on 2020-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_player_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='card1State',
            field=models.CharField(default='HIDDEN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='card2State',
            field=models.CharField(default='HIDDEN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
